### ISSUE TITLE
训练时的错误

### ISSUE THREAD

**Issue by Snlblkb** [YoYo000/MVSNet#100]
Training MVSNet with totally 3 views inputs (including reference view)
Training sample number:  27097
Traceback (most recent call last):
  File "train.py", line 435, in <module>
    tf.app.run()
  File "/home/pc/anaconda3/envs/MVSnet/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 430, in main
    train(sample_list)
  File "train.py", line 275, in train
    image = tf.image.per_image_standardization(image)                   
  File "/home/pc/anaconda3/envs/MVSnet/lib/python2.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 821, in per_image_standardization
    _Check3DImage(image, require_static=False), image)
  File "/home/pc/anaconda3/envs/MVSnet/lib/python2.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 135, in _Check3DImage
    image.shape)
ValueError: 'image' (shape (?, ?, ?, 3)) must be three-dimensional.
 是我输入数据的路径问题么
tf.app.flags.DEFINE_string('dtu_data_root', '/home/pc/MVSNet-master/mvsnet/Data/mvsnet_github_data/data/dtu',
这个是在train中改的路径
dtu文件夹下有Cameras Depths Rectified 三个文件夹

**Comment by dengyangyan** [comment]
请问你解决这个问题了吗~

**Comment by TheRealPoseidon** [comment]
> 请问你解决这个问题了吗~

请问您解决这个问题了吗~

**Comment by dengyangyan** [comment]
建议直接跑pytorch版本的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月2日(周四) 下午3:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YoYo000/MVSNet] 训练时的错误 (#100)




  
请问你解决这个问题了吗~
  
请问您解决这个问题了吗~
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TheRealPoseidon** [comment]
感谢 您指这个吗
https://github.com/xy-guo/MVSNet_pytorch

**Comment by dengyangyan** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月2日(周四) 下午3:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YoYo000/MVSNet] 训练时的错误 (#100)




 
感谢 您指这个吗
 https://github.com/xy-guo/MVSNet_pytorch
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiYaolab** [comment]
@Snlblkb 请问您解决这个问题了吗？

**Comment by XQQ1072448274** [comment]
您好 问题解决了吗

**Comment by zccz6** [comment]
您好 问题解决了吗

**Comment by lgc1030** [comment]
您好，我也遇到了相同的问题，请问您解决了吗？
