### ISSUE TITLE
test  ValueError: No variables to save

### ISSUE THREAD

**Issue by Ttingyyy** [YoYo000/MVSNet#155]
Traceback (most recent call last):
  File "test.py", line 273, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\tensorflow_1.x_gpu\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\Anaconda3\envs\tensorflow_1.x_gpu\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "D:\Anaconda3\envs\tensorflow_1.x_gpu\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "test.py", line 268, in main
    mvsnet_pipeline(mvs_list)
  File "test.py", line 216, in mvsnet_pipeline
    restorer = tf.train.Saver(tf.global_variables())
  File "D:\Anaconda3\envs\tensorflow_1.x_gpu\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "D:\Anaconda3\envs\tensorflow_1.x_gpu\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\Anaconda3\envs\tensorflow_1.x_gpu\lib\site-packages\tensorflow_core\python\training\saver.py", line 865, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by Tz7311** [comment]
楼主，是否已经解决了？我也遇到同样的问题
