### ISSUE TITLE
About test set results

### ISSUE THREAD

**Issue by tiffany61706** [YoYo000/MVSNet#2]
Dear author:
Thanks for your work and open source of MVSNet!
I have some trouble during the test set results.
I use your code step by step to generate the result depths of test sets; however, in the terminal there is some error coming out (error message is at the bottom). And I have rechecking my tensorflow version is 1.9.0. Looks like the error coming from the dim between this two tensors in the gather_nd. Maybe there is some problem that I have not find out yet. Please help me. thanks again
----------------------------------------------------------------------------------------------------------------------------
tiffany@tiffany-System-Product-Name:~/Downloads/MVSNet/mvsnet$ python test.py --dense_folder ../scan9/
Testing MVSNet with 5 views
sample number:  49
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
3D with 8 filters
2018-08-31 19:30:31.197754: I Pre-trained model restored from /home/tiffany/Downloads/compare/scan9/model/model.ckpt-70000 
left information:[[[0.970263 0.00747983 0.241939]]...]
fronto_direction information:[[[-0.241605 -0.030951 0.969881]]]
left information:[[[0.970263 0.00747983 0.241939]]...]
fronto_direction information:[[[-0.241605 -0.030951 0.969881]]]
left information:[[[0.970263 0.00747983 0.241939]]...]
fronto_direction information:[[[-0.241605 -0.030951 0.969881]]]
left information:[[[0.970263 0.00747983 0.241939]]...]
fronto_direction information:[[[-0.241605 -0.030951 0.969881]]]
Traceback (most recent call last):
  File "test.py", line 252, in <module>
    tf.app.run()
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "test.py", line 239, in main
    mvsnet_pipeline(mvs_list)
  File "test.py", line 198, in mvsnet_pipeline
    [depth_map, init_depth_map, prob_map, croped_images, scaled_cams, image_index])
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[301, :] = [0, 192, 1, 13] does not index into param (shape: [1,192,216,288]).
	 [[Node: GatherNd_3 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](soft_arg_min/prob_volume, stack_5)]]

Caused by op u'GatherNd_3', defined at:
  File "test.py", line 252, in <module>
    tf.app.run()
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "test.py", line 239, in main
    mvsnet_pipeline(mvs_list)
  File "test.py", line 162, in mvsnet_pipeline
    centered_images, scaled_cams, FLAGS.max_d, depth_start, depth_interval)
  File "/data1/Downloads/MVSNet/mvsnet/model.py", line 241, in inference_mem
    prob_map = get_propability_map(probability_volume, estimated_depth_map, depth_start, depth_interval)
  File "/data1/Downloads/MVSNet/mvsnet/model.py", line 61, in get_propability_map
    prob_map_right1 = tf.gather_nd(cv, voxel_coordinates_right1)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3051, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[301, :] = [0, 192, 1, 13] does not index into param (shape: [1,192,216,288]).
	 [[Node: GatherNd_3 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](soft_arg_min/prob_volume, stack_5)]]
----------------------------------------------------------------------------------------------------------------------------------

**Comment by YoYo000** [comment]
Hi  @tiffany61706 ,

I did not try to run with tensorflow 1.9 before. I think I could look into it on Monday. Could you first try roll back to tensorflow 1.5?

Mean while have you modified the test settings (e.g., max_d, max_h?)

Yao

**Comment by MoranChen** [comment]
Dear author:
I wish we can have a QQ group or weixin group that can discuss the problem.

**Comment by YoYo000** [comment]
Sure @MoranChen 

You could send your wechat account to me by email.

**Comment by YoYo000** [comment]
@tiffany61706 Could you try the lasted update? Thanks

**Comment by tiffany61706** [comment]
Dear author: 
I have try you new update in my environment and I get new error at the line of refined depth map in model.py 281. The error message is at below.
tiffany@tiffany-System-Product-Name:~/Downloads/MVSNet/mvsnet$ python test.py --dense_folder ../scan9/
Testing MVSNet with 5 views
sample number:  49
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
3D with 8 filters
2018-09-03 16:23:54.165202: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-03 16:23:58.116425: I Pre-trained model restored from /home/tiffany/Downloads/MVSNet/model/model.ckpt-70000 
Traceback (most recent call last):
  File "test.py", line 256, in <module>
    tf.app.run()
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "test.py", line 243, in main
    mvsnet_pipeline(mvs_list)
  File "test.py", line 202, in mvsnet_pipeline
    [depth_map, init_depth_map, prob_map, croped_images, scaled_cams, image_index])
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,1,216,288] vs. [1,216,288,1]
	 [[Node: add_6 = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, Tile)]]

Caused by op u'add_6', defined at:
  File "test.py", line 256, in <module>
    tf.app.run()
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "test.py", line 243, in main
    mvsnet_pipeline(mvs_list)
  File "test.py", line 170, in mvsnet_pipeline
    depth_map = depth_refine(init_depth_map, ref_image, FLAGS.max_d, depth_start, depth_interval)
  File "/data1/Downloads/MVSNet/mvsnet/model.py", line 281, in depth_refine
    refined_depth_map = tf.multiply(norm_depth_map, depth_scale_mat) + depth_start_mat
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 907, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 183, in add
    "Add", x=x, y=y, name=name)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/tiffany/anaconda3/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,1,216,288] vs. [1,216,288,1]
	 [[Node: add_6 = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, Tile)]]

**Comment by tiffany61706** [comment]
Dear author: 
I solve the problem by adding this line(os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2') in line 10  in test.py. 
And I can run the test code.  Thanks for helping me solve this problem.  The terminal message is at the bottom. I will close this issue. 
-----------------------------------------------------------------------------------------------------------------------------------
tiffany@tiffany-System-Product-Name:~/Downloads/MVSNet/mvsnet$ python test.py --dense_folder ../scan9/
Testing MVSNet with 5 views
sample number:  49
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
3D with 8 filters
2018-09-03 16:32:36.895333: I Pre-trained model restored from /home/tiffany/Downloads/MVSNet/model/model.ckpt-70000 
2018-09-03 16:34:42.514603: I depth inference 0 finished. (125.466 sec/step) 
2018-09-03 16:36:31.392223: I depth inference 1 finished. (108.853 sec/step) 
2018-09-03 16:38:19.735435: I depth inference 2 finished. (108.338 sec/step) 
2018-09-03 16:40:09.171527: I depth inference 3 finished. (109.430 sec/step) 
2018-09-03 16:41:57.857290: I depth inference 4 finished. (108.681 sec/step) 
2018-09-03 16:43:46.826156: I depth inference 5 finished. (108.963 sec/step) 
2018-09-03 16:45:34.948691: I depth inference 6 finished. (108.116 sec/step) 
2018-09-03 16:47:22.432686: I depth inference 7 finished. (107.479 sec/step) 
2018-09-03 16:49:10.017361: I depth inference 8 finished. (107.579 sec/step)

**Comment by YoYo000** [comment]
Glad to hear that! 

BTW are you using the CPU to run the test? It seems like it is quite slow on your machine. For me it takes ~2s to process one frame on a GTX 1080ti GPU.

**Comment by tiffany61706** [comment]
Yes. How could I switch to the GPU device?

**Comment by tiffany61706** [comment]
I think that I have installed the tensorflow with cpu version. So I use anaconda to reinstall my tensorflow in gpu version. The code now is running on the gpu. I update the tensorflow version to 1.10.0 and test code still work. Thanks author again. (I put the install code and terminal message in the below)  
-----------------------------------------------------------------------------------------------------------------------------------
conda install -c anaconda tensorflow-gpu
-----------------------------------------------------------------------------------------------------------------------------------
tiffany@tiffany-System-Product-Name:~/Downloads/MVSNet/mvsnet$ python test.py --dense_folder ../scan9/
Testing MVSNet with 5 views
sample number:  49
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
2D with 32 filters
3D with 8 filters
2018-09-03 17:05:55.952343: I Pre-trained model restored from /home/tiffany/Downloads/MVSNet/model/model.ckpt-70000 
2018-09-03 17:06:21.114409: I depth inference 0 finished. (25.003 sec/step) 
2018-09-03 17:06:23.004632: I depth inference 1 finished. (1.885 sec/step) 
2018-09-03 17:06:24.995765: I depth inference 2 finished. (1.974 sec/step) 
2018-09-03 17:06:26.856654: I depth inference 3 finished. (1.856 sec/step) 
2018-09-03 17:06:28.782221: I depth inference 4 finished. (1.910 sec/step) 
2018-09-03 17:06:30.672573: I depth inference 5 finished. (1.878 sec/step) 
2018-09-03 17:06:32.555843: I depth inference 6 finished. (1.873 sec/step) 
2018-09-03 17:06:34.505337: I depth inference 7 finished. (1.945 sec/step) 
2018-09-03 17:06:36.417418: I depth inference 8 finished. (1.901 sec/step) 
2018-09-03 17:06:38.313775: I depth inference 9 finished. (1.891 sec/step) 
2018-09-03 17:06:40.254375: I depth inference 10 finished. (1.934 sec/step) 
2018-09-03 17:06:42.218417: I depth inference 11 finished. (1.956 sec/step) 
2018-09-03 17:06:44.389021: I depth inference 12 finished. (2.166 sec/step) 
2018-09-03 17:06:47.229780: I depth inference 13 finished. (2.814 sec/step) 
2018-09-03 17:06:49.790588: I depth inference 14 finished. (2.545 sec/step) 
2018-09-03 17:06:52.156664: I depth inference 15 finished. (2.354 sec/step) 
2018-09-03 17:06:54.432517: I depth inference 16 finished. (2.261 sec/step) 
2018-09-03 17:06:56.659950: I depth inference 17 finished. (2.207 sec/step) 
2018-09-03 17:06:58.830293: I depth inference 18 finished. (2.153 sec/step) 
2018-09-03 17:07:01.071824: I depth inference 19 finished. (2.222 sec/step) 
2018-09-03 17:07:03.271607: I depth inference 20 finished. (2.185 sec/step) 
2018-09-03 17:07:05.342295: I depth inference 21 finished. (2.052 sec/step) 
2018-09-03 17:07:07.405104: I depth inference 22 finished. (2.057 sec/step) 
2018-09-03 17:07:09.451198: I depth inference 23 finished. (2.027 sec/step) 
2018-09-03 17:07:11.502295: I depth inference 24 finished. (2.037 sec/step) 
2018-09-03 17:07:13.503813: I depth inference 25 finished. (1.983 sec/step) 
2018-09-03 17:07:15.413596: I depth inference 26 finished. (1.905 sec/step) 
2018-09-03 17:07:17.419975: I depth inference 27 finished. (1.993 sec/step) 
2018-09-03 17:07:19.433406: I depth inference 28 finished. (2.004 sec/step) 
2018-09-03 17:07:21.349053: I depth inference 29 finished. (1.911 sec/step) 
2018-09-03 17:07:23.269608: I depth inference 30 finished. (1.909 sec/step) 
2018-09-03 17:07:25.215312: I depth inference 31 finished. (1.939 sec/step) 
2018-09-03 17:07:27.287911: I depth inference 32 finished. (2.055 sec/step) 
2018-09-03 17:07:29.318514: I depth inference 33 finished. (2.013 sec/step)

**Comment by tiffany61706** [comment]
Dear author 
I have visualized results about the depth map and the probability map. But I can not get the exactly same images as yours. Have you change the draw palette in plt.imshow?
-----------------------------------------------------------------------------------------------------------------------------------
depth map:
![figure_1-1](https://user-images.githubusercontent.com/39460180/44979008-91c37700-af9e-11e8-97ec-b3c22d9f1936.png)

-----------------------------------------------------------------------------------------------------------------------------------
probability map:
![figure_1](https://user-images.githubusercontent.com/39460180/44979014-98ea8500-af9e-11e8-89f5-2998a4028418.png)

**Comment by YoYo000** [comment]
@tiffany61706 This depth map have been filtered by the probability threshold 0.8 (in order to produce the final point cloud, which is related to my recent commit). 

If you want to generate the depth map as the cover figure, please simply return the unfiltered depth map by:

return estimated_depth_map, prob_map

in inference_mem(), model.py

**Comment by MoranChen** [comment]
Dear author:
My wechat account is chenmoran19940928.  Very glad to see your reply!

**Comment by progressforever** [comment]
Sorry, I have some problems during testing process. I donn't have the dense_folder(test datasets) refered in code(test.py). Can you give me a link for downloading this dataset? Thank you~
