### ISSUE TITLE
Testing won't run

### ISSUE THREAD

**Issue by erezposner** [YoYo000/MVSNet#64]
I have followed the instruction and downloaded both models and data.

Upon run I get this error below:
this seems to happen at "load model" line 218. please help
thank you
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Repositories/MVSNet/mvsnet/test.py", line 273, in <module>
    tf.app.run()
  File "C:\Users\erez.posner\AppData\Local\Continuum\anaconda3\envs\tensorflow0\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:/Repositories/MVSNet/mvsnet/test.py", line 269, in main
    mvsnet_pipeline(mvs_list)
  File "D:/Repositories/MVSNet/mvsnet/test.py", line 218, in mvsnet_pipeline
    restorer = tf.train.Saver(tf.global_variables())
  File "C:\Users\erez.posner\AppData\Local\Continuum\anaconda3\envs\tensorflow0\lib\site-packages\tensorflow\python\training\saver.py", line 832, in __init__
    self.build()
  File "C:\Users\erez.posner\AppData\Local\Continuum\anaconda3\envs\tensorflow0\lib\site-packages\tensorflow\python\training\saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\erez.posner\AppData\Local\Continuum\anaconda3\envs\tensorflow0\lib\site-packages\tensorflow\python\training\saver.py", line 869, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

**Comment by HaloKim** [comment]
Tensorflow not support Python 2.7 in Windows.

**Comment by erezposner** [comment]
I am not using python 2.7. I am using python 3.6.

**Comment by YoYo000** [comment]
@erezposner have you downloaded the pretrained model and set its path?

**Comment by erezposner** [comment]
Yes.
- I placed all testing data in \MVSNet\TEST_DATA_FOLDER, so now it contains \cams and \images and pair.txt. 
- I placed all model files in \MVSNet\MODEL_FOLDER
In train.py I updated the following lines:
- I updated in test.py the model_dir path 
```
tf.app.flags.DEFINE_string('model_dir',
                           r'D:\Repositories\MVSNet\MODEL_FOLDER',
                           """Path to restore the model.""")
```
finally I ran the following command 
```
--dense_folder D:\Repositories\MVSNet\TEST_DATA_FOLDER --regularization '3DCNNs' --max_w 1152 --max_h 864 --max_d 192 --interval_scale 1.06
```

**Comment by YoYo000** [comment]
I am not sure if it is about the environment setup as I did not run the code on python3 as well as windows... Maybe you could try python 2.7 on windows first?

**Comment by YoYo000** [comment]
running with python 3 indeed encounters some problems as reported by other users

**Comment by erezposner** [comment]
Changed OS to linux
