### ISSUE TITLE
How to get [gt_depthmap] ?

### ISSUE THREAD

**Issue by HaloKim** [YoYo000/MVSNet#66]
Hi yoyo,
I'm having a hard time learning.
You say, I need [reference_image, source_images, reference_camera, source_cameras, reference_gt_depthmap].

So I had preapare COLMAP dataset.

![image](https://user-images.githubusercontent.com/44603549/62681511-cfbdec00-b9f4-11e9-8e40-e4a7962dc829.png)

![image](https://user-images.githubusercontent.com/44603549/62681479-bfa60c80-b9f4-11e9-8f81-abec28b380cb.png)

![image](https://user-images.githubusercontent.com/44603549/62681572-f5e38c00-b9f4-11e9-9441-00978a066aab.png)

This datases is COLMAP data set.
But When I check DTU dataset, That is consist of [depth map pfm] and [pdepth visual png],
So, How can i get depth visual file ?
I could use rainbow depth map with your **visualize.py**
But Error.
How can I do...
`2019-08-08 15:45:23.672483: W tensorflow/core/framework/op_kernel.cc:1198] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'astype'
2019-08-08 15:45:23.672576: W tensorflow/core/framework/op_kernel.cc:1198] Unknown: exceptions.AttributeError: 'NoneType' object has no attribute 'astype'
	 [[Node: PyFunc = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_1"](arg0)]]
Traceback (most recent call last):
  File "/home/git/MVSNet-master/mvsnet/train.py", line 356, in <module>
    tf.app.run()
  File "/home/git/anaconda2/envs/train.py/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/git/MVSNet-master/mvsnet/train.py", line 351, in main
    train(sample_list)
  File "/home/git/MVSNet-master/mvsnet/train.py", line 316, in train
    [summary_op, train_opt, loss, less_one_accuracy, less_three_accuracy])
  File "/home/git/anaconda2/envs/train.py/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/git/anaconda2/envs/train.py/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/git/anaconda2/envs/train.py/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/git/anaconda2/envs/train.py/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.AttributeError: 'NoneType' object has no attribute 'astype'
	 [[Node: PyFunc = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_1"](arg0)]]
	 [[Node: Model_tower0/IteratorGetNext = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]`

**Comment by YoYo000** [comment]
There is no GT depth map unless you use the laser scan to acquire the ground truth point cloud.
