### ISSUE TITLE
Problems when testing on custom data set

### ISSUE THREAD

**Issue by Beniko95J** [YoYo000/MVSNet#78]
Hi, I am trying to evaluate R-MVSNet on my own data set. I have succeeded to run R-MVSNet on scan9 and got the fused point cloud, but I meet some problems when running R-MVSNet on custom data set.

I generate the test data using colmap2mvsnet.py provided by you, and the log is as follows:

```
intrinsic[1]
 [[317.954   0.    388.008]
 [  0.    318.567 234.158]
 [  0.      0.      1.   ]]

extrinsic[1]
 [[ 0.97552621 -0.21949121 -0.01312175 -0.281522  ]
 [-0.02957683 -0.07185136 -0.99697601  0.607734  ]
 [ 0.21788479  0.97296432 -0.07658472 -1.1366    ]
 [ 0.          0.          0.          1.        ]]

depth_ranges[1]
 (0.7309697383190406, 0.006800571336574068, 210.95552712983584, 2.1587872780735013)

view_sel[0]
 [(5, 25.260626027244793), (6, 21.993219417884873), (7, 18.92430382544663), (4, 17.39796267622522), (9, 16.20083763365206), (3, 15.613958052412684), (11, 13.398583718814804), (8, 12.724461358041392), (12, 12.513881286019865), (10, 12.365354568182251)]
```

Then I copied the generated files to the dense_folder and run the following command. BTW, the image size of my test data is 752x480

```
~ python mvsnet/test.py --dense_folder structure_notexture --regularization 'GRU' --max_w 376 --max_h 240 --max_d 256 --interval_scale 0.8
```

However, I got some error messages as follows

```
sample number:  193
2D UNet with 32 channel output
2D UNet with 32 channel output
2D UNet with 32 channel output
2D UNet with 32 channel output
2D UNet with 32 channel output
2019-10-25 20:54:08.075949: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-25 20:54:08.122346: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-25 20:54:08.122680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 980 Ti major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:01:00.0
totalMemory: 5.94GiB freeMemory: 5.06GiB
2019-10-25 20:54:08.122696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-10-25 20:54:08.383733: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-25 20:54:08.383763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-10-25 20:54:08.383769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-10-25 20:54:08.383902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4822 MB memory) -> physical GPU (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0, compute capability: 5.2)
2019-10-25 20:54:09.044229: I Pre-trained model restored from MODEL_FOLDER/tf_model/GRU/model.ckpt-100000 
2019-10-25 20:54:10.732470: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-10-25 20:54:10.765523: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
range:  0.73097 0.0054408 210.955527 2.158787
range:  0.618166 0.0061600000000000005 238.329723 2.445499
2019-10-25 20:54:11.404178: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x56491f1e0dd0
Traceback (most recent call last):
  File "mvsnet/test.py", line 273, in <module>
    tf.app.run()
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "mvsnet/test.py", line 269, in main
    mvsnet_pipeline(mvs_list)
  File "mvsnet/test.py", line 231, in mvsnet_pipeline
    [init_depth_map, prob_map, scaled_images, scaled_cams, image_index])
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,30,48,64] vs. shape[1] = [1,30,47,64]
	 [[node 2dconcat5_0_2 (defined at /home/benik/Documents/MVSNet/cnn_wrapper/network.py:438)  = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](transpose_153, 2dconv3_2/relu_2, 2dconcat5_0_2/axis)]]
	 [[{{node while/RefExit/_289}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_14605_while/RefExit", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'2dconcat5_0_2', defined at:
  File "mvsnet/test.py", line 273, in <module>
    tf.app.run()
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "mvsnet/test.py", line 269, in main
    mvsnet_pipeline(mvs_list)
  File "mvsnet/test.py", line 198, in mvsnet_pipeline
    depth_num, depth_start, depth_end, reg_type='GRU', inverse_depth=FLAGS.inverse_depth)
  File "/home/benik/Documents/MVSNet/mvsnet/model.py", line 351, in inference_winner_take_all
    view_tower = UNetDS2GN({'data': view_image}, is_training=True, reuse=True)
  File "/home/benik/Documents/MVSNet/cnn_wrapper/network.py", line 81, in __init__
    self.setup()
  File "/home/benik/Documents/MVSNet/cnn_wrapper/mvsnet.py", line 80, in setup
    .concat(axis=-1, name='2dconcat5_0')
  File "/home/benik/Documents/MVSNet/cnn_wrapper/network.py", line 40, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/benik/Documents/MVSNet/cnn_wrapper/network.py", line 438, in concat
    return tf.concat(values=input_tensors, axis=axis, name=name)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1124, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1033, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/benik/anaconda3/envs/mvsnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,30,48,64] vs. shape[1] = [1,30,47,64]
	 [[node 2dconcat5_0_2 (defined at /home/benik/Documents/MVSNet/cnn_wrapper/network.py:438)  = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](transpose_153, 2dconv3_2/relu_2, 2dconcat5_0_2/axis)]]
	 [[{{node while/RefExit/_289}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_14605_while/RefExit", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

I think the generated files are right. Am I using wrong parameters to run on my own data set or something else that causes these errors?

Best regards

**Comment by YoYo000** [comment]
could you change --max_w to 384

also, are you input images of the same resolution?

**Comment by Beniko95J** [comment]
Yes, all the input images are of the same resolution.

After I change --max_w to 384, there is no error message now! I have just started to study about MVSNet and could you please explain this to me?

**Comment by YoYo000** [comment]
Current version R-MVSNet applies a U-Net to extract the 2D image features, so the width and height of the input images must be divisible by 16 :)

**Comment by Beniko95J** [comment]
Thank you for the quick reply. And now I have another problem: the resolution of generated depth map is too low(the size is 96 x 60). Do I need to do some pre-processings to get a high resolution depth map?

**Comment by ZDLLLL** [comment]
@Beniko95J Hello.Can share how you get the depth information of the image?
